# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'LumosDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LumosDemo
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'Lumos', :path => '../'
end
